### ISSUE TITLE
clean movie script

### ISSUE THREAD

**Issue by jihwanp** [movienet/movienet-tools#15]
Hello, Is there any script or tool that is organized like the script in the data picture at the top image in this link: [movienet overview](http://movienet.site/projects/eccv20movienet.html)? I downloaded the script data and it was like crawling data. By the way, thank you for making good data.

**Comment by ycxioooong** [comment]
Hi @jihwanp, we do have internal tools for parsing the scripts, and it will be cleaned for public usage.

**Comment by jihwanp** [comment]
I'll wait . Thank u!

**Comment by derrxb** [comment]
Hi, sorry to bring up a closed thread. But do you guys have any further info on this?
