### ISSUE TITLE
movienet.site is not accessible

### ISSUE THREAD

**Issue by Wenjun-Peng** [movienet/movienet-tools#34]
It seems that the server break down again, could you fix it?

**Comment by ycxioooong** [comment]
Hi there, our MovieNet website is banned by our DNSPod service provider due to "adult content". Please use https://movienet.github.io/ instead.

**Comment by Wenjun-Peng** [comment]
> Hi there, our MovieNet website is banned by our DNSPod service provider due to "adult content". Please use https://movienet.github.io/ instead.

Thanks a lot.
