### ISSUE TITLE
Installation Issue--NameError: name 'CUDAExtension' is not defined

### ISSUE THREAD

**Issue by camCX** [movienet/movienet-tools#9]
hey,

Your work is so beautiful ! But i need your help。

**I successfully installed the requirements with pip.But after the step3 (`python setup.py `develop`) or `python -m pip install -e . -U`, I got an error message:**

`ERROR: Command errored out with exit status 1:
     command: /home/mist/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/mist/camcode/movienet/movienet-tools/setup.py'"'"'; __file__='"'"'/home/mist/camcode/movienet/movienet-tools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /home/mist/camcode/movienet/movienet-tools/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/mist/camcode/movienet/movienet-tools/setup.py", line 211, in <module>
        ] if EXT_TYPE else [],
      File "/home/mist/camcode/movienet/movienet-tools/setup.py", line 106, in make_cuda_ext
        return CUDAExtension(
    NameError: name 'CUDAExtension' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

Here is my  environment ：

- Ubuntu 18.04, 

- 2080Ti, 

- GCC 7.5, 

- CUDA10.2, 

- Pytorch 1.6.0, 

- mmcv 1.0.3

- python 3.7

Thanks！

**Comment by ycxioooong** [comment]
Hi there,

Thanks for posting the bug. It's fixed now. Please pull the newest code and rebuild ``movienet-tools``.
